apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: lento
  name: meu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Disponível somente em 1 nó
  persistentVolumeReclaimPolicy: Retain
  hostPath: # armazenamento no nó
    path: /mnt/data
  storageClassName: giropops
